/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "./stencil-public-runtime";
import { Color } from "./interface";
export namespace Components {
    interface DstnyButton {
        "backgroundColor"?: 'primary' | 'light' | 'dark';
        "disabled"?: boolean;
        "label": string;
        /**
          * Function to focus the Dstny Button.
         */
        "setFocus": () => Promise<void>;
        "size"?: 'small' | 'large';
        /**
          * The type of the button.
         */
        "type": 'submit' | 'reset' | 'button';
        "variant"?: Color;
    }
}
declare global {
    interface HTMLDstnyButtonElement extends Components.DstnyButton, HTMLStencilElement {
    }
    var HTMLDstnyButtonElement: {
        prototype: HTMLDstnyButtonElement;
        new (): HTMLDstnyButtonElement;
    };
    interface HTMLElementTagNameMap {
        "dstny-button": HTMLDstnyButtonElement;
    }
}
declare namespace LocalJSX {
    interface DstnyButton {
        "backgroundColor"?: 'primary' | 'light' | 'dark';
        "disabled"?: boolean;
        "label"?: string;
        "onButtonClicked"?: (event: CustomEvent<any>) => void;
        /**
          * Emitted when the button loses focus.
         */
        "onDstnyBlur"?: (event: CustomEvent<void>) => void;
        /**
          * Emitted when the button has focus.
         */
        "onDstnyFocus"?: (event: CustomEvent<void>) => void;
        "size"?: 'small' | 'large';
        /**
          * The type of the button.
         */
        "type"?: 'submit' | 'reset' | 'button';
        "variant"?: Color;
    }
    interface IntrinsicElements {
        "dstny-button": DstnyButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dstny-button": LocalJSX.DstnyButton & JSXBase.HTMLAttributes<HTMLDstnyButtonElement>;
        }
    }
}
