/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DstnyButton {
        "disabled"?: boolean;
        "label": string;
        "size"?: 'small' | 'large';
        "variant"?: 'primary' | 'secondary' | 'tertiary';
    }
}
declare global {
    interface HTMLDstnyButtonElement extends Components.DstnyButton, HTMLStencilElement {
    }
    var HTMLDstnyButtonElement: {
        prototype: HTMLDstnyButtonElement;
        new (): HTMLDstnyButtonElement;
    };
    interface HTMLElementTagNameMap {
        "dstny-button": HTMLDstnyButtonElement;
    }
}
declare namespace LocalJSX {
    interface DstnyButton {
        "disabled"?: boolean;
        "label"?: string;
        "onButtonClicked"?: (event: CustomEvent<any>) => void;
        "size"?: 'small' | 'large';
        "variant"?: 'primary' | 'secondary' | 'tertiary';
    }
    interface IntrinsicElements {
        "dstny-button": DstnyButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dstny-button": LocalJSX.DstnyButton & JSXBase.HTMLAttributes<HTMLDstnyButtonElement>;
        }
    }
}
